openapi: "3.0.3"
info:
  title: MS Project API
  version: 1.0.0
  description: De API for testing the discriminator in openapi 6
paths:
  /api/projects:
    post:
      summary: Create a project
      operationId: createProjects
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
                - $ref: '#/components/schemas/Lizard'
              discriminator:
                propertyName: petType
      responses:
        201:
          description: OK

components:
  schemas:
    Cat:
      type: object
      # all other properties specific to a `Cat`
      required:
        - petType
      properties:
        catName:
          type: string
        petType:
          type: string
    Dog:
      type: object
      # all other properties specific to a `Dog`
      required:
        - petType
      properties:
        bark:
          type: string
        petType:
          type: string
    Lizard:
      type: object
      # all other properties specific to a `Lizard`
      required:
        - petType
      properties:
        lovesRocks:
          type: boolean
        petType:
          type: string