openapi: 3.0.3
info:
  description: De API for testing the discriminator in openapi 6
  title: MS Pet API
  version: 1.0.0
servers:
- url: /
paths:
  /api/projects:
    get:
      operationId: getPets
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PetResponse'
                type: array
          description: Succes respons
      summary: get a pet
      tags:
      - pets
      x-accepts: application/json
components:
  schemas:
    PetResponse:
      discriminator:
        propertyName: petType
      oneOf:
      - $ref: '#/components/schemas/Cat'
      - $ref: '#/components/schemas/Dog'
      - $ref: '#/components/schemas/Lizard'
    Cat:
      properties:
        catName:
          type: string
        petType:
          type: string
      required:
      - petType
      type: object
    Dog:
      properties:
        bark:
          type: string
        petType:
          type: string
      required:
      - petType
      type: object
    Lizard:
      properties:
        lovesRocks:
          type: boolean
        petType:
          type: string
      required:
      - petType
      type: object

