openapi: 3.0.3
info:
  description: De API for testing the discriminator in openapi 6
  title: MS Project API
  version: 1.0.0
servers:
- url: /
paths:
  /api/projects:
    post:
      operationId: createProjects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createProjects_request'
        required: true
      responses:
        "201":
          description: OK
      summary: Create a project
      tags:
      - projects
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    Cat:
      properties:
        catName:
          type: string
        petType:
          type: string
      required:
      - petType
      type: object
    Dog:
      properties:
        bark:
          type: string
        petType:
          type: string
      required:
      - petType
      type: object
    Lizard:
      properties:
        lovesRocks:
          type: boolean
        petType:
          type: string
      required:
      - petType
      type: object
    createProjects_request:
      discriminator:
        propertyName: petType
      oneOf:
      - $ref: '#/components/schemas/Cat'
      - $ref: '#/components/schemas/Dog'
      - $ref: '#/components/schemas/Lizard'
      type: object

